---
data: 22/11/2022
format:
  pdf:
    include-in-header:
      text: |
        \usepackage{stmaryrd}
        \usepackage{xfrac}
---

# Exercice 1

Soit le problème de Cauchy suivant :
$$
\forall t > 0, \quad y' \left ( t \right ) = t + y \left ( t \right )
$$

avec la condition initiale
$$
y \left ( 0 \right ) = 1.
$$


1. Trouver la solution exacte de ce problème.
1. Appliquer la méthode explicite d'Euler à ce problème, avec $\tau = 0.1$ puis évaluer la solution en $t = 0.3$. Comparer à la solution exacte.

# Exercice 2

Soit le problème de Cauchy suivant :
$$
\forall t > 0, \quad y' \left ( t \right ) = 2t - y \left ( t \right )
$$

avec la condition initiale
$$
y \left ( 0 \right ) = 1.
$$

1. Trouver la solution exacte de ce problème.
1. Appliquer le schéma implicite d'Euler à ce problème, avec $\tau = 0.1$ puis évaluer la solution en $t = 0.3$. Comparer à la solution exacte.
1. Quelle difficulté rencontre t'on avec ce schéma pour l'équation suivante
$$
\forall t > 0, \quad y' \left ( t \right ) = 2t - y \left ( t \right ) ^ 2 \quad ?
$$

# Exercice 3

Soit l'équation différentielle ordinaire
$$
\forall t > 0, \quad y''' \left ( t \right ) - y'' \left ( t \right ) + 2 y' \left ( t \right ) - y \left ( t \right ) + 2 = 0
$$
où la solution est soumise aux conditions initiales
$$
\left \{ \begin{aligned}
y \left ( 0 \right ) & = 0, \\
y' \left ( 0 \right ) & = 1, \\
y'' \left ( 0 \right ) & = 2.
\end{aligned} \right .
$$

1. Transformer cette équation en un système d'équations différentielles ordinaires d'ordre $1$.
1. Modifier la fonction `julia` suivante (qui correspond au système du pendule simple avec une pulsation unitaire) en fonction de la réponse à la question précédente :

	`rhs(t, y1, y2) = (y2, -sin(y1))`

# Le problème de Blasius

Le problème de Blasius décrit l'écoulement stationnaire et incompressible en 2 dimensions dans la couche limite se formant sur une plaque plane semi-infinie parallèle à l'écoulement.

Il s'écrit sous la forme d'un problème aux limites :
$$
u''' \left ( x \right ) + u \left ( x \right ) u'' \left ( x \right ) = 0
$$
où la variable dépendante $u$ vérifie les conditions aux limites
$$
\left \{ \begin{aligned}
u \left ( 0 \right ) & = 0, \\
u' \left ( 0 \right ) & = 0, \\
u' \left ( \infty \right ) & = 1.
\end{aligned} \right .
$$

1. Quel est le degré de cette EDO ? La réécrire sous la forme d'un système d'EDO d'ordre 1.
1. Montrer que l'équation de Blasius et les conditions en $0$ sont inchangées par la transformation ($c \ne 0$)
$$
\begin{aligned}
\overline{u} & \leftarrow c u, \\
\overline{x} & \leftarrow x / c.
\end{aligned}
$$
$\overline{u}$ est donc soumis à la même équation que $u$, à l'exception de la condition en $\infty$ qui est remplacée par :
$$
\overline{u}'' \left ( 0 \right ) = 1.
$$

On définit alors
$$
\alpha = \overline{u}' \left ( \infty \right ).
$$

3. Montrer que le choix de la constante $c = \sqrt{\alpha}$ mène à
$$
u' \left ( \infty \right ) = 1.
$$

